"""players, game events, error reports

Revision ID: 0001
Revises: 
Create Date: 2026-09-30 21:38:58.210225

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '0001'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('players',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('player_hash', sa.String(length=64), nullable=False),
    sa.Column('first_seen', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('last_seen', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('platform', sa.String(length=32), nullable=True),
    sa.Column('app_version', sa.String(length=64), nullable=True),
    sa.Column('os_version', sa.String(length=128), nullable=True),
    sa.Column('device_model', sa.String(length=128), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('player_hash')
    )
    op.create_table('error_reports',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('player_id', sa.BigInteger(), nullable=True),
    sa.Column('occurred_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('received_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('fingerprint', sa.String(length=64), nullable=False),
    sa.Column('source', sa.String(length=128), nullable=False),
    sa.Column('summary', sa.String(length=500), nullable=False),
    sa.Column('app_version', sa.String(length=64), nullable=True),
    sa.Column('commit', sa.String(length=64), nullable=True),
    sa.Column('platform', sa.String(length=32), nullable=True),
    sa.Column('os_version', sa.String(length=128), nullable=True),
    sa.Column('device_model', sa.String(length=128), nullable=True),
    sa.Column('body', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['player_id'], ['players.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('error_reports', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_error_reports_fingerprint'), ['fingerprint'], unique=False)
        batch_op.create_index('ix_error_reports_occurred_at', ['occurred_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_error_reports_player_id'), ['player_id'], unique=False)

    op.create_table('game_events',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('player_id', sa.BigInteger(), nullable=False),
    sa.Column('session_id', sa.UUID(), nullable=True),
    sa.Column('type', sa.String(length=48), nullable=False),
    sa.Column('occurred_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('received_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('app_version', sa.String(length=64), nullable=True),
    sa.Column('data', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.ForeignKeyConstraint(['player_id'], ['players.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('game_events', schema=None) as batch_op:
        batch_op.create_index('ix_game_events_occurred_at', ['occurred_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_game_events_player_id'), ['player_id'], unique=False)
        batch_op.create_index('ix_game_events_type_occurred_at', ['type', 'occurred_at'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('game_events', schema=None) as batch_op:
        batch_op.drop_index('ix_game_events_type_occurred_at')
        batch_op.drop_index(batch_op.f('ix_game_events_player_id'))
        batch_op.drop_index('ix_game_events_occurred_at')

    op.drop_table('game_events')
    with op.batch_alter_table('error_reports', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_error_reports_player_id'))
        batch_op.drop_index('ix_error_reports_occurred_at')
        batch_op.drop_index(batch_op.f('ix_error_reports_fingerprint'))

    op.drop_table('error_reports')
    op.drop_table('players')
    # ### end Alembic commands ###
